/**
 * Declarative forwarding of execution-domain OMP settings to the companion.
 *
 * The companion builds its ToolSession from `Settings.isolated()`, which knows
 * nothing about the user's `config.yml`. Keys listed here are the ones the 12
 * remote-executed native tools actually read at execution time and whose value
 * changes behaviour without changing a tool's wire schema. Everything else is
 * deliberately not forwarded:
 *
 * - schema-affecting keys (`async.enabled`, `memory.backend`, `skillful`,
 *   `eval.*`, `edit.mode`) are pinned by the worker so the admission handshake
 *   stays deterministic;
 * - approval keys (`bash.patterns`, `bash.allowCompoundCommands`) are evaluated
 *   locally by the native approval callback the wrapper preserves;
 * - `worktree.clone` would rewrite `git worktree add` into a call to the worker
 *   binary itself, so the worker pins it off.
 */

export type ForwardedSettingSpec =
  | { type: "boolean" }
  | { type: "number"; min?: number; max?: number }
  | { type: "enum"; values: readonly string[] }
  | { type: "interceptor-rules" };

export const FORWARDED_EXECUTION_SETTINGS = {
  "tools.maxTimeout": { type: "number", min: 0 },
  "bash.direnv": { type: "enum", values: ["auto", "off"] },
  "bash.direnvLoadTimeoutMs": { type: "number", min: 0 },
  "bashInterceptor.enabled": { type: "boolean" },
  "bashInterceptor.patterns": { type: "interceptor-rules" },
  "grep.contextBefore": { type: "number", min: 0 },
  "grep.contextAfter": { type: "number", min: 0 },
  "read.defaultLimit": { type: "number", min: 1 },
  "read.renderMarkdown": { type: "boolean" },
  "read.summarize.enabled": { type: "boolean" },
  "read.summarize.prose": { type: "boolean" },
  "read.summarize.minTotalLines": { type: "number", min: 0 },
  "read.summarize.minBodyLines": { type: "number", min: 0 },
  "read.summarize.minCommentLines": { type: "number", min: 0 },
  "read.summarize.unfoldLimit": { type: "number", min: 0 },
  "read.summarize.unfoldUntil": { type: "number", min: 0 },
  "images.autoResize": { type: "boolean" },
  "edit.fuzzyMatch": { type: "boolean" },
  "edit.fuzzyThreshold": { type: "number", min: 0, max: 1 },
  "edit.enforceSeenLines": { type: "boolean" },
  "edit.blockAutoGenerated": { type: "boolean" },
  "lsp.formatOnWrite": { type: "boolean" },
  "lsp.diagnosticsOnWrite": { type: "boolean" },
  "lsp.diagnosticsOnEdit": { type: "boolean" },
  "lsp.diagnosticsDeduplicate": { type: "boolean" },
} as const satisfies Record<string, ForwardedSettingSpec>;

export type ForwardedSettingKey = keyof typeof FORWARDED_EXECUTION_SETTINGS;
export const FORWARDED_SETTING_KEYS = Object.keys(
  FORWARDED_EXECUTION_SETTINGS,
) as ForwardedSettingKey[];

export type RemoteExecutionSettings = Partial<Record<ForwardedSettingKey, unknown>>;

/** Minimal read surface of an OMP `Settings` instance. */
export interface SettingsReader {
  get(path: string): unknown;
  isConfigured?(path: string): boolean;
}

function isInterceptorRule(value: unknown): boolean {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return false;
  const rule = value as Record<string, unknown>;
  if (typeof rule.pattern !== "string" || typeof rule.tool !== "string" || typeof rule.message !== "string")
    return false;
  if (rule.flags !== undefined && typeof rule.flags !== "string") return false;
  if (
    rule.allowSubcommands !== undefined &&
    !(Array.isArray(rule.allowSubcommands) && rule.allowSubcommands.every((entry) => typeof entry === "string"))
  )
    return false;
  return true;
}

export function isValidForwardedSetting(key: ForwardedSettingKey, value: unknown): boolean {
  const spec: ForwardedSettingSpec = FORWARDED_EXECUTION_SETTINGS[key];
  switch (spec.type) {
    case "boolean":
      return typeof value === "boolean";
    case "number":
      return (
        typeof value === "number" &&
        Number.isFinite(value) &&
        (spec.min === undefined || value >= spec.min) &&
        (spec.max === undefined || value <= spec.max)
      );
    case "enum":
      return typeof value === "string" && spec.values.includes(value);
    case "interceptor-rules":
      return Array.isArray(value) && value.every(isInterceptorRule);
  }
}

/**
 * Capture the forwardable subset of local settings. Only explicitly configured
 * keys are captured (when the reader can tell), so the companion keeps OMP
 * defaults for everything the user never set and the handshake payload stays
 * small.
 */
export function captureExecutionSettings(settings: SettingsReader): RemoteExecutionSettings {
  const captured: RemoteExecutionSettings = {};
  for (const key of FORWARDED_SETTING_KEYS) {
    if (settings.isConfigured && !settings.isConfigured(key)) continue;
    let value: unknown;
    try {
      value = settings.get(key);
    } catch {
      continue;
    }
    if (value === undefined || !isValidForwardedSetting(key, value)) continue;
    captured[key] = value;
  }
  return captured;
}

/**
 * Accept a wire payload on the companion: unknown keys are dropped and typed
 * keys must validate; a malformed value is a protocol error rather than a
 * silent fallback because the local host produced it from typed settings.
 */
export function parseExecutionSettings(value: unknown): RemoteExecutionSettings {
  if (value === undefined) return {};
  if (typeof value !== "object" || value === null || Array.isArray(value))
    throw new Error("Protocol field settings must be an object");
  const record = value as Record<string, unknown>;
  const parsed: RemoteExecutionSettings = {};
  for (const key of FORWARDED_SETTING_KEYS) {
    if (!(key in record)) continue;
    const entry = record[key];
    if (!isValidForwardedSetting(key, entry))
      throw new Error(`Protocol setting ${key} has an invalid value`);
    parsed[key] = entry;
  }
  return parsed;
}
